# -*- Makefile -*-

include ../../circle-stdlib/Config.mk
CIRCLEHOME = ../../circle-stdlib/libs/circle

LIBVTERM=../../build/libvterm.a

$(LIBVTERM): encoding/DECdrawing.inc encoding/uk.inc $(LIBVTERM)($(patsubst %.c,%.o,$(wildcard *.c)))
	rm -f encoding/DECdrawing.inc encoding/uk.inc

encoding/%.inc: encoding/%.tbl
	@echo TBL $<
	@perl -CSD ../tbl2inc_c.pl $< >$@

include $(CIRCLEHOME)/Rules.mk
CFLAGS += -I ../include
